name: pr-workflow

on:
  pull_request:

permissions:
  contents: write

jobs:
  golang-pr:
    runs-on: ubuntu-latest
    env:
        working-directory: ./cmd/aws-ip-lookup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
     
      - name: Go prep
        working-directory: ${{ env.working-directory }}
        run: |
            go vet
            go mod tidy
            go mod vendor

      - name: Run GoSec Security Scanning
        uses: securego/gosec@master
        with:
          args: ./...