# .github/workflows/release.yml
name: goreleaser

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main 
    tags:
      - "v*"

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
        working-directory: ./cmd/aws-ip-lookup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
     
      - name: Go prep
        working-directory: ${{ env.working-directory }}
        run: go vet
             go mod tidy && go mod vendor

      - name: Run GoSec Security Scanning
        uses: securego/gosec@master
        with:
          args: ./...
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}